config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bikes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'bikes#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
# frozen_string_literal: true

class Bike < ApplicationRecord
  has_one_attached :image
  belongs_to :style
  has_many :bike_visitings
  before_create :update_price

  scope :by_name, ->(name_filter) { where('lower(name) LIKE ?', "%#{name_filter.downcase}%") }
  scope :by_price_larger_than, ->(price_larger_than_filter) { where('price > ?', price_larger_than_filter) }
  scope :by_price_lower_than, ->(price_lower_than_filter) { where('price < ?', price_lower_than_filter) }
  scope :by_style, ->(style_filter) { where(style_id: style_filter) }
  scope :order_by_visitings, lambda {
                               Bike.left_outer_joins(:bike_visitings).group('bikes.id').order('count(bikes.id) DESC')
                             }

  def update_price
    self.price = PriceGeneratorService.new(name, price).generate_price
  end

  def new_visit
    BikeVisiting.create(bike: self)
  end
end

app/models/bike_visiting.rb
class BikeVisiting < ApplicationRecord
  belongs_to :bike
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :bikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
# frozen_string_literal: true

class BikesController < ApplicationController
  before_action :set_bike, only: %i[show edit update destroy]
  before_action :authenticate_admin_user!, except: %i[index show]
  after_action :update_bike_visiting, only: :show
  has_scope :by_name
  has_scope :by_price_lower_than
  has_scope :by_price_larger_than
  has_scope :by_style
  has_scope :order_by_visitings


  # GET /bikes or /bikes.json
  def index
    @bikes = apply_scopes(Bike.order_by_visitings).all
  end

  # GET /bikes/1 or /bikes/1.json
  def show; end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit; end

  # POST /bikes or /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        # format.html { redirect_to bike_url(@bike), notice: "Bike was successfully created." }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1 or /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        # format.html { redirect_to bike_url(@bike), notice: "Bike was successfully updated." }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1 or /bikes/1.json
  def destroy
    @bike.destroy

    respond_to do |format|
      # format.html { redirect_to bikes_url, notice: "Bike was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def update_bike_visiting
    return if session[@bike.id]
    session[@bike.id] = @bike.id
    @bike.new_visit
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_bike
    @bike = Bike.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bike_params
    params.require(:bike).permit(:name, :desc, :style_id, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bikes/_bike.html.erb
<div id="<%= dom_id bike %>">
  <div class="bg-white shadow-md rounded-md flex flex-col p-4">
    <div class="p-4 flex justify-between items-center  flex-grow">
      <div class="aspect-w-16 aspect-h-9 overflow-hidden w-6/12 h-36 flex justify-center items-center">
        <% if bike.image.attached? %>
          <%= image_tag(bike.image, class: "object-cover") %>
        <% end %>
      </div>
      <div class="flex flex-col gap-y-3">
        <h2 class="text-lg text-red-900 font-bold"> <%= bike.name %></h2>
        <p class="text-gray-600">Style:
          <span class="bg-red-200 p-1.5 rounded-lg">
          <%= bike.style.name %>
        </span></p>
        <p class="text-gray-600">Visits: <span class="font-bold"><%= bike.bike_visitings.count %></span></p>
        <p class="text-gray-600">Price: $<%= bike.price %></p>
        <% if action_name != "show" %>
          <%= link_to "View Details", bike,
                      class: "self-center w-fit bg-gray-600 text-white py-2 px-4 rounded-md hover:bg-gray-100 hover:text-black" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bikes/_form.html.erb
<%= form_with(model: bike, class: "contents") do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
        <% bike.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block  rounded-md outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :desc %>
    <%= form.text_area :desc, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bike</h1>

  <%= render "form", bike: @bike %>

  <%= link_to "Show this bike", @bike, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to bikes", bikes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bikes/index.html.erb
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div id="bikes" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-y-10 gap-x-20 w-full  p-10">
  <%= render @bikes %>
  </div>

app/views/bikes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New bike</h1>

  <%= render "form", bike: @bike %>

  <%= link_to 'Back to bikes', bikes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bikes/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div id="<%= dom_id @bike %>">
      <div class="bg-white flex p-4">
        <div class="aspect-w-16 aspect-h-9 overflow-hidden w-5/12 ">
          <% if @bike.image.attached? %>
            <%= image_tag(@bike.image, class: "object-cover") %>
          <% end %>
        </div>
        <div class="p-4 flex flex-col gap-y-2 flex-grow w-5/12">
          <h2 class="text-lg text-red-900 font-bold mb-2"> <%= @bike.name %></h2>
          <p class="text-gray-600">Style: <span class="bg-red-200 p-1.5 rounded-lg"><%= @bike.style.name %></span></p>
          <p class="text-gray-600">Price: $<%= @bike.price %></p>
          <p class="text-gray-600"> <%= @bike.desc %></p>
          <% if action_name != "show" %>
            <%= link_to "View Details", @bike,
                        class: "self-center w-fit bg-gray-600 text-white py-2 px-4 rounded-md hover:bg-gray-100 hover:text-black" %>
          <% end %>
        </div>
      </div>
    </div>
    <%= link_to 'Back to bikes', bikes_path,
                class: "mt-5 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium
                  hover:bg-gray-600 hover:text-white" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ride</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <main class="flex flex-col h-full">
    <%= render template: 'components/header' %>
    <div class="flex h-screen fixed top-20 w-full">
      <div class="w-4/12 md-w-2/12 bg-gray-50 border-r border-gray-200 ">
        <%= render template: 'components/filter_form' %>
      </div>
      <div class="w-10/12 h-full bg-slate-50 overflow-auto">
        <%= yield %>
      </div>
    </div>
  </main>
  </body>
</html>